version: '3.9'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    env_file:
      - .env
    restart: always

  evolutionapi:
    image: asabocinski/evolutionapi:latest
    container_name: evolutionapi
    ports:
      - "8080:8080" # Ajuste a porta para corresponder à configuração da API
    env_file:
      - .env
    volumes:
      - ./evolution-data:/evolution/store # Diretório de persistência de dados
    restart: always
